### ISSUE TITLE
 Add "terminal-recording" topic to this repo

### ISSUE THREAD

**Issue by katrinleinweber** [elisescu/tty-record#1]
As an educator, I'd like to be able to advertise the concept of creating animations from the terminal. Thus, I like to link to https://github.com/topics/terminal-recording instead of collecting several tool links.

How about `goscript` joins the small club and also adds the topic `terminal-recording` to this repo?

**Comment by elisescu** [comment]
@katrinleinweber, I can see it already has that topic, but I don't remember adding it (perhaps I just forgot). Anyways, it shows up in the link you mentioned, so should be good. Thanks for the suggestion :)

**Comment by katrinleinweber** [comment]
Cool 😃 Too bad GitHub doesn't store / read such metadata from `.gitattributes` or some other file within the repo 🤔
