### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by fvcr** [elisescu/tty-record#3]
Hi @elisescu,

Thanks for the good work!
Please add license information so we can package tty-record for Debian.

**Comment by elisescu** [comment]
Thx for the PR, merged that in, so closing this

**Comment by fvcr** [comment]
Hi, I packaged tty-record for [Debian](https://tracker.debian.org/tty-record) and [AUR](https://aur.archlinux.org/packages/tty-record).

[![Packaging status](https://repology.org/badge/vertical-allrepos/tty-record.svg)](https://repology.org/project/tty-record/versions)

**Comment by elisescu** [comment]
This is great. Thanks, @fvcr ! :)
